services:
  beastz_document:
    container_name: beastz_document
    build:
      context: .
      args:
        NEXT_PUBLIC_BACKEND_BASE_URL: ${NEXT_PUBLIC_BACKEND_BASE_URL}
        NEXT_PUBLIC_VAULT_URL: ${NEXT_PUBLIC_VAULT_URL}
        NEXT_PUBLIC_SOCKET_URL: ${NEXT_PUBLIC_SOCKET_URL}
    ports:
      - 34000:3000
