services:
  beastz_document:
    container_name: beastz_document
    build:
      context: .
      args:
        NEXT_PUBLIC_BACKEND_BASE_URL: test
        NEXT_PUBLIC_VAULT_URL: test
        NEXT_PUBLIC_SOCKET_URL: test
    ports:
      - 34000:3000
