import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { cn } from '@/lib/utils';
import { Inter as FontSans } from 'next/font/google';
import { getSignInUrl, getSignUpUrl, getUser } from '@workos-inc/authkit-nextjs';
import { LandingPageContent } from '@/components/app/root';
import { AppLayout } from '@/components/app/app-layout';

import '../styles/globals.css';

const ThemeProvider = dynamic(() => import('../components/theme-provider'), { ssr: false });

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by next app',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const [userInfo, signInUrl, signUpUrl] = await Promise.all([
    getUser(),
    getSignInUrl(),
    getSignUpUrl(),
  ]);

  console.log(userInfo);

  if (!userInfo.user) {
    //TODO: static page here
    //! here will be like opening page like static page

    return (
      <>
        <html lang="en">
          <body>
            <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
              <LandingPageContent signInUrl={signInUrl} signUpUrl={signUpUrl} />
            </ThemeProvider>
          </body>
        </html>
      </>
    );
  }

  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
          <AppLayout userInfo={userInfo}>{children}</AppLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
